# Generated by Django 5.2 on 2025-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nero", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stat",
            field=models.CharField(default="india", max_length=50),
            preserve_default=False,
        ),
    ]
