# Generated by Django 5.1.7 on 2025-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="underConstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_under_construction", models.BooleanField(default=False)),
                (
                    "Uc_note",
                    models.TextField(
                        blank=True,
                        help_text="Note for underconstruction mode",
                        null=True,
                    ),
                ),
                (
                    "uc_duration",
                    models.DateTimeField(
                        blank=True,
                        help_text="END date and Time for under construction",
                        null=True,
                    ),
                ),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
