# Generated by Django 5.2.4 on 2025-07-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_to_many", "0002_teacher_test_remove_onetomany_user_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="techerstudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="one_to_many.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="one_to_many.teacher",
                    ),
                ),
            ],
        ),
    ]
