# Generated by Django 5.2.1 on 2025-05-14 12:47

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=1)),
                ("locality", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "pin",
                    models.PositiveIntegerField(
                        help_text="Enter 6-digit pin code",
                        validators=[app1.models.pin_lenght_validate],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andaman & Nicobar Island", "Andaman & Nicobar Island"),
                            ("Andhra pradesh", "Andhra pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("chandigarh", "chandigarh"),
                            ("Dadar & Nagar Haveli", "Dadar & Nagar Haveli"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Gujrat", "Gujrat"),
                            ("Dehli", "Dehli"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="Write 10 Digit Mobile number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("job_city", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="profileimg"),
                ),
                ("my_file", models.FileField(blank=True, upload_to="doc")),
            ],
        ),
    ]
