# Generated by Django 5.2.4 on 2025-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NF1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="course_multi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                (
                    "course_choice",
                    models.CharField(
                        choices=[("AI", "AI"), ("ML", "ML"), ("GENAI", "GenAI")]
                    ),
                ),
            ],
        ),
    ]
