# Generated by Django 5.2.4 on 2025-07-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_examcenter_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="data_Student",
            fields=[
                (
                    "examcenter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.examcenter",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("roll", models.IntegerField()),
            ],
            bases=("app.examcenter",),
        ),
    ]
